---
# handlers file for wfly
- name: alternatives
  alternatives:
    name: java
    link: /usr/bin/java
    path: /opt/java/bin/java
    priority: 1
- alternatives:
    name: javac
    link: /usr/bin/javac
    path: /opt/java/bin/javac
    priority: 1
- alternatives:
    name: javaws
    link: /usr/bin/javaws
    path: /opt/java/bin/javaws
    priority: 1

- name: wildfly start
  systemd: 
    name: wildfly.service
    state: restarted

- name: cleanup
  file:
    path: /opt/jdk-8u131-linux-x64.tar.gz
    state: absent
- file:
    path: "/opt/{{ wildfly_tgz }}"
    state: absent

- name: symlink logs
  file:
    src: /opt/wildfly/standalone/log
    dest: /var/log/wildfly/log
    owner: jboss
    group: jboss
    state: link

- name: notify
  slack:
    token: token/generated/slack
    msg: '{{ inventory_hostname }} Wildfly install completed'
    channel: "#ansible_linux"
    username: "bot_user"
