---
# handlers file for wfly
- name: alternatives
  alternatives:
    name: java
    link: /usr/bin/java
    path: /opt/java/bin/java
    priority: 1
- alternatives:
    name: javac
    link: /usr/bin/javac
    path: /opt/java/bin/javac
    priority: 1
- alternatives:
    name: javaws
    link: /usr/bin/javaws
    path: /opt/java/bin/javaws
    priority: 1

- name: wildfly start
  systemd: 
    name: wildfly.service
    state: restarted

- name: cleanup
  file:
    path: "{{ app_root }}jdk-8u{{ jdkver }}-linux-x64.tar.gz"
    state: absent
- file:
    path: "{{ app_root }}{{ wildfly_tgz }}"
    state: absent

- name: symlink logs
  file:
    src: "{{ app_root }}wildfly/standalone/log"
    dest: /var/log/wildfly/log
    owner: jboss
    group: jboss
    state: link

- name: notify slack
  slack:
    token: token/generated/slack
    msg: '{{ inventory_hostname }} Wildfly install completed'
    channel: "#ansible_linux"
    username: "bot_user"

- name: notify email
  mail: 
    host: localhost
    port: 25
    username: emailaddr@owens.org
    password: passhere
    to: Admins <Admins@owens.org>
    subject: "Wildfly Install"
    body: "Wildlfy install completed {{ ansible_hostname }}"
