# ACLs 
- name: audit acls
  hosts: vbox1.owens.dev
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  vars_files: 
    - ~/vault.yaml

  vars:
    - ansible_ssh_user: "{{ me }}"

  tasks:
    - name: set acls
      acl:
        path: "/mnt/test"
        entity: rowens 
        etype: user
        permissions: rwx
        default: yes
        recalculate_mask: mask
        state: present


