# ACLs 
- name: audit acls
  hosts: centos
  become: yes
  become_user: root
  become_method: su
  gather_facts: no

  vars_files: 
    - ~/vault.yaml

  vars:
    - ansible_ssh_user: "{{ me }}"

  tasks:
    - name: set acls
      acl:
        path: "/mnt/testdir"
        entity: billy 
        etype: user
        permissions: r
        default: yes


