---
# collectd.yml
# Author: Robert Owens (xxxxxx)
#collectd-curl_json-5.5.0-1.el6.x86_64
#collectd-disk-5.5.0-1.el6.x86_64
#collectd-utils-5.5.0-1.el6.x86_64
#libcollectdclient-5.5.0-1.el6.x86_64
#collectd-python-5.5.0-1.el6.x86_64
#collectd-5.5.0-1.el6.x86_64

- name: collectd
  hosts: hostlist
  become: yes
  become_method: su
  become_user: root
  vars_files:
    - ../vault.yaml
  vars:
    ansible_become_pass: "{{ root }}"

  tasks:
    - name: logrotate configuration
      copy: src=../files/collectd dest=/etc/logrotate.d/ owner=root group=root mode=0644 force=no

    - name: Create collectd.d Directory
      file: path=/etc/collectd.d state=directory mode=0755

    - name: Create prestage directory
      file: path=/opt/wildfly/standalone/prestage state=directory mode=0755
 
    - name: wildfly.conf
      copy: src=../files/wildfly.conf.java8 dest=/etc/collectd.d/wildfly.conf owner=root group=root mode=0644

    - name: collectd.conf
      copy: src=../files/collectd.conf.0615 dest=/etc/collectd.conf owner=root group=root mode=0644

    - name: prestage jolokia
      copy: src=../files/jolokia.war dest=/opt/wildfly/standalone/prestage/ owner=jboss group=jboss force=no

    - name: Install curl_json
      yum: name=collectd-curl_json state=present disable_gpg_check=yes 

    - name: Restart collectd
      service: name=collectd state=restarted
