---
- name: common
  hosts: all:!localhost
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: patch boxes
    yum: 
      name: '*'
      state: latest

  - name: git install
    yum:
      name: git.x86_64
      state: present
  
  - name: docker remove old
    yum: 
      name: ['docker-client', 'docker-client-latest', 'docker-common', 'docker-latest', 'docker-latest-logrotate', 'docker-logrotate', 'docker-engine']
      state: absent

  - name: docker repo
    yum:
      name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
      state: latest

  - name: add docker repo
    shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

  - name: install docker
    yum: 
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      state: present

  - name: enable firewalld
    systemd:
      name: firewalld
      enabled: yes
      state: started
    
