---
- name: common
  hosts: all:!localhost
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: patch boxes
    yum: 
      name: '*'
      state: latest

  - name: common packages
    yum:
      name: ['git.x86_64', 'unzip', 'yum-utils', 'device-mapper-persistent-data', 'lvm2']
      state: present
  
  - name: docker remove old
    yum: 
      name: ['docker-client', 'docker-client-latest', 'docker-common', 'docker-latest', 'docker-latest-logrotate', 'docker-logrotate', 'docker-engine']
      state: absent

  - name: add docker repo
    shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

  - name: docker packages
    yum: 
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      state: present

  - name: enable firewalld
    systemd:
      name: firewalld
      enabled: yes
      state: started
   
  - name: terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.5/terraform_0.12.5_linux_amd64.zip 
      dest: /usr/local/bin
      remote_src: yes
    tags: ['never', 'terraform']
