---
# top cpu usage example
# NOTE: command cannot process pipes, shell can.
- name: cpu
  hosts: wildfly
  gather_facts: false
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: cpu
      shell: ps -Ao user,uid,comm,pid,pcpu --sort=-pcpu | head -11
      register: cpuout

    - debug: var=cpuout.stdout_lines
