---
- name: stop
  hosts: swarm
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: stop
      systemd:
        name: firewalld
        state: stopped
      tags: stop

    - name: start
      systemd:
        name: firewalld
        state: started
      tags: start