---
# Hacked from https://github.com/adithyakhamithkar/ansible-playbooks/blob/master/get-thread-dump.yml
# ansible-playbook get-thread-dump.yml --extra-vars "java_bin=/opt/java/bin dest=/tmp"
# Vars to be passed:
# java_bin=directory containing the jstat command
# dest=local directory to store the dump
#
- name: Thread Dump
  hosts: wildfly
  become: yes
  become_method: su
  become_user: root
  vars:
    jstat: /opt/java/bin/jstat
    dest: /tmp
    process: wildfly

  tasks:
  - name: Get PID
    shell: "ps -ef | grep {{ process }} | grep -v ansible | grep -v grep | awk '{print $2}'"
    register: pid

  - name: Take thread dump
    shell: "{{ jstat }} -gc {{pid.stdout}} 1s 30 >> thread-dump-{{hostname}}.txt"

  - name: Copy thread dump
    fetch: 
      src: /root/thread-dump-{{hostname}}.txt 
      dest: "{{ dest }}/"
      flat: yes

  - name: Clean up
    file: 
      path: "/root/thread-dump-{{ hostname }}.txt"
      state: absent
