all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    main:
      hosts:
        desk.owens.dev:
    swarm:
      hosts:
        vbox1.owens.dev:
          role: leader
        vbox[2:3].owens.dev:
