---
- name: k8s
  hosts: box
  become: yes
  become_method: su
  become_user: root

  vars_files:
    - ~/vault.yaml

  vars:
    - ansible_become_pass: "{{ root_remote }}"
#curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
    - version: v1.17.3

  tasks:
    - name: get kubectl
      get_url: 
        url: https://storage.googleapis.com/kubernetes-release/release/{{ version }}/bin/linux/amd64/kubectl
        dest: /usr/local/bin
        mode: 0755
        owner: root
        group: root
