---
# Linuix Network Connectivity
- name: NetworkConnectivity
  hosts: wildfly
  gather_facts: false
  become: no
  become_method: su
  become_user: root

  tasks:
#Show server IP address
    - name: facts
      setup: 
        filter: ansible_default_ipv4*
      register: factout

#Show routes
    - name: route
      command: /sbin/route -n
      register: routeout

#Show established connections
    - name: netstatestab
      command: /bin/netstat -antp | grep ESTAB 
      register: netstatout

    - debug: var=factout
    - debug: var=routeout.stdout_lines
    - debug: var=netstatout.stdout_lines



