---
- name: patch rhel
  hosts: swarm
  become: yes
  become_method: sudo
  become_user: root
#  roles:
#    - common

  tasks:
  - name: patch boxes
    yum: 
      name: '*'
      state: latest
#      exclude: kernel*
