---
- name: patch rhel
  hosts: vbox3.owens.dev vbox2.owens.dev
  become: yes
  become_method: sudo
  become_user: root
#  roles:
#    - common

  tasks:
  - name: patch boxes
    yum: 
      name: '*'
      state: latest
      exclude: kernel*
