---
# test inventory changes
# test become
- name: uptime
  hosts: swarm

  vars_files:
    - ~/vault.yaml

  tasks:
    - name: uptime
      command: /usr/bin/uptime
      register: uptime
    - debug:
        var: uptime.stdout_lines
