---
# test inventory changes
# test become
- name: uptime
  hosts: rancher
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - ~/vault.yaml

  vars:
    ansible_ssh_pass: "{{ sudo }}"
    ansible_become_pass: "{{ sudo }}"

  tasks:
    - name: uptime
      command: /usr/bin/uptime
      register: uptime
    - debug:
        var: uptime.stdout_lines
