---
- name: stop
  hosts: centos
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: stop
      service:
        name: wildfly
        state: stopped
      when:
       - ansible_os_family == "RedHat"
       - ansible_distribution_major_version == "6"
    - systemd:
        name: wildfly
        state: stopped
      when:
       - ansible_os_family == "RedHat"
       - ansible_distribution_major_version =="7"
  
