---
#rm -f /opt/jdk-8u131-linux-x64.tar.gz
#rm -f /opt/wildfly-10.1.0.Final.tar.gz
#rm -rf /opt/jdk1.8.0_131
#rm -rf /opt/wildfly-10.1.0.Final
#systemctl stop wildfly.service
#systemctl disable wildfly.service
#rm /etc/systemd/system/[servicename]
#rm /etc/systemd/system/[servicename] symlinks that might be related
#systemctl daemon-reload
#systemctl reset-failed
- name: wildfly uninstall
  hosts: centos
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: disable systemd
      systemd:
        name: wildfly.service
        state: stopped
      ignore_errors: yes
    - systemd:
        name: wildfly.service
        enabled: no
        daemon_reload: yes
      ignore_errors: yes
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version == "7"

    - name: systemd reset-failed
      command: systemctl reset-failed
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version == "7"

    - name: remove systemd file
      file:
        path: /etc/systemd/service/wildfly.service
        state: absent
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version == "7"

    - name: disable services
      service:
        name: wildfly
        enabled: no
        state: stopped
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version == "6"

    - name: remove service file
      file:
        path: /etc/init.d/wildfly
        state: absent
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version == "6"

    - name: remove files and directories 
      file:
        path: /opt/jdk-8u131-linux-x64.tar.gz
        state: absent
    - file:
        path: /opt/wildfly-10.1.0.Final.tar.gz
        state: absent
    - file:
        path: /opt/wildfly-10.1.0.Final
        state: absent
    - file:
        path: /opt/jdk1.8.0_131
        state: absent
    - file:
        path: /var/log/wildfly
        state: absent
    - file:
        path: /opt/wildfly
        state: absent
    - file:
        path: /opt/java
        state: absent

# alternatives --remove <name> <path>
    - name: remove alternatives
      command: /sbin/alternatives --remove java /opt/java/bin/java
      ignore_errors: yes

