---
# tasks file for jolokia
#
- name: get jolokia
  get_url:
    name: "{{ jolokia_url }}"
    dest: /tmp/jolokia.war
    owner: jboss
    group: jboss

- name: deploy
   jboss:
     src: /tmp/jolokia.war
     deployment: hello.war
     state: present
