---
# tasks file for jolokia
#
- name: get jolokia
  get_url:
    name: "{{ jolokia_url }}"
    dest: /tmp/jolokia.war
    owner: jboss
    group: jboss

- name: deploy
   jboss:
     src: /tmp/jolokia.war
     deployment: jolokia.war
     state: present

- name: systemd restart
  systemd: 
    name: wildfly.service
    state: restarted
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"
                
- name: service restart
  service:
    name: wildfly
    state: restarted
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "6"